### ISSUE TITLE
Testing in 5.7

### ISSUE THREAD

**Issue by dataindataout** [kedarvj/mysql-random-data-generator#2]
Tested on various data types in MySQL 5.7.20. Works well except for the new datatype "geometry." Results below.

>CREATE TABLE `ugly` (
  `ID` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `animals` enum('cow','giraffe','kangaroo','buffalo','seal') DEFAULT NULL,
  `weight` float(8,4) DEFAULT NULL,
  `price` decimal(7,2) DEFAULT NULL,
  `copyright` year(4) DEFAULT NULL,
  `orderdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `groupid` smallint(5) unsigned DEFAULT NULL,
  `letter` char(1) DEFAULT NULL,
  `picture` blob,
  `createdate` datetime DEFAULT NULL,
  `g` geometry DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

>mysql> call populate('test','ugly',100,'N');
ERROR 1416 (22003): Cannot get geometry object from data you send to the GEOMETRY field

>mysql> alter table ugly drop column g;
Query OK, 0 rows affected (0.05 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> call populate('test','ugly',100,'N');
...
1 row in set (1.37 sec)

Query OK, 0 rows affected (1.37 sec)

Sample row:
>ID: 9932419
name: AExwPMpntgyZCOmTHGmmATPtwbToMUoJGeCAUURzSVXdxbPYvfrqDVR XoAPvFUFviGFllxEFqLKsFcrDSEsZWJHhNwRXkfZGhRMlSEyzbLAxHWIEYctIkcFYXSxHXQkAcJq DsacjLfuDMYIuVuneIeuIjWgQMlSGFiZwkJRimMcWCXhSQBl SOqmnARIQfbPZzzYtXFo IUvuLxaLGZeuLyfiAfVoI  aDOmPrmlsdrzssKyixN ismfRVbtM
animals: seal
weight: 1373.7651
price: 64858.56
copyright: 1983
orderdate: 2012-03-16 18:39:00
groupid: 54
letter: g
picture: 83a31448f44ba9ab3a05e352386dc524
createdate: 2012-05-22 12:01:10

**Comment by kedarvj** [comment]
This has been ["fixed" here](https://github.com/kedarvj/mysql-random-data-generator/commit/51593e31916c912ef148023ee41f8b4b6abc8623#diff-91658b080ed144dfad7c6bb7c39af890). Script isn't (yet) generating the random values but NULLs for those types and letting others continue. 


Thanks & [Regards.]
