### ISSUE TITLE
ERROR 1172 (42000): Result consisted of more than one row

### ISSUE THREAD

**Issue by bishoykamal** [kedarvj/mysql-random-data-generator#7]
This error
ERROR 1172 (42000): Result consisted of more than one row
appear when trying to call populate_fk to a child table.
Is this the correct way to use it or i am using it wrong? and how to use the two scripts to populate my database

**Comment by cyrishikesh** [comment]
> This error
> ERROR 1172 (42000): Result consisted of more than one row
> appear when trying to call populate_fk to a child table.
> Is this the correct way to use it or i am using it wrong? and how to use the two scripts to populate my database

@bishoykamal  ADD one more  condition `CONSTRAINT_NAME <> 'PRIMARY'` to  **where** clause of  **concat** query in populate_fk.sql file.

**Comment by ihsankl** [comment]
i get this error too while trying to populate more than 1 FK in a table. For 1 FK, it's fine.
![image](https://user-images.githubusercontent.com/55323174/149648632-e3f3c9d2-0ef2-4578-a512-5a7b093d3926.png)

**Comment by khasanshadiyarov** [comment]
Anyone find a solution so far?

**Comment by kedarvj** [comment]
Thanks for reporting @bishoykamal and reminding @khasandesign. This has been fixed.
